# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    docker-compose.yml                                 :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: mdoquocb <mdoquocb@student.42quebec.com>   +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/04/02 20:08:18 by mdoquocb          #+#    #+#              #
#    Updated: 2023/04/02 20:08:37 by mdoquocb         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

version: '3'
services:
  build:
    build:
      context: ..
      dockerfile: Dockerfile

