name: CI

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macOS-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: compile project
        run: cmake -B build

      - name: recompile project
        run: |
          make re

      - name: Clean project
        run: |
          make finish

      - name: Run Unit test
        working-directories: build
        run: ctest
